
name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12']
        python-arch: [x64]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}-${{ matrix.python-arch }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Initialize Submodules
      run: |
        git submodule update --init --recursive

    - name: Prepare Linux Environment
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install xvfb libglu1-mesa-dev freeglut3-dev mesa-common-dev

    - name: Prepare Windows Environment
      if: runner.os == 'Windows'
      uses: ssciwr/setup-mesa-dist-win@v2

    - name: Install
      run: |
        poetry install
      env:
        EGRAPHICS_BUILD_WITH_COVERAGE: ${{ matrix.os == 'windows-latest' && '0' || '1' }}

    - name: Test
      if: runner.os != 'Linux'
      run: |
        poetry run pytest --cov=egraphics --cov-report=xml -vvx
      env:
        LIBGL_ALWAYS_SOFTWARE: "true"

    - name: Test with Xvfb
      if: runner.os == 'Linux'
      run: |
        xvfb-run -a poetry run pytest --cov=egraphics --cov-report=xml -vvx
      env:
        LIBGL_ALWAYS_SOFTWARE: "true"

    - name: Codecov
      uses: codecov/codecov-action@v2


  static-analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
        architecture: x64

    - name: Upgrade pip & setuptools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools

    - name: Install Pre-Commit
      run: |
        python -m pip install pre-commit

    - name: Static Analysis
      run: |
        python -m pre_commit run --all-files

