
name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2025, macos-latest]
        python-version: ['3.12']
        python-arch: [x64]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}-${{ matrix.python-arch }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}

    - name: Install Poetry
      uses: snok/install-poetry@v1.4.1

    - name: Install ninja
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Setup MSVC
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Initialize Submodules
      run: |
        git submodule update --init --recursive

    - name: Prepare Linux Environment
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install xvfb libglu1-mesa-dev freeglut3-dev mesa-common-dev

    - name: Prepare Windows Environment
      if: runner.os == 'Windows'
      uses: ssciwr/setup-mesa-dist-win@v2

    - name: Build SDL
      working-directory: vendor/SDL
      run: |
        cmake . -GNinja -DCMAKE_BUILD_TYPE=Release -DSDL_TESTS=0 -DSDL_TESTS_LIBRARY=0
        cmake --build . --config Release

    - name: Install
      run: |
        poetry install
      env:
        EGRAPHICS_BUILD_WITH_COVERAGE: ${{ matrix.os == 'windows-2025' && '0' || '1' }}

    - name: Test
      if: runner.os != 'Linux'
      run: |
        export DYLD_LIBRARY_PATH=$PWD/vendor/SDL:$DYLD_LIBRARY_PATH
        poetry run pytest --cov=egraphics --cov-report=xml
      env:
        LIBGL_ALWAYS_SOFTWARE: "true"

    - name: Test with Xvfb
      if: runner.os == 'Linux'
      run: |
        export LD_LIBRARY_PATH=$PWD/vendor/SDL:$LD_LIBRARY_PATH
        xvfb-run -a poetry run pytest --cov=egraphics --cov-report=xml
      env:
        LIBGL_ALWAYS_SOFTWARE: "true"

    - name: Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}


  static-analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
        architecture: x64

    - name: Install Poetry
      uses: snok/install-poetry@v1.4.1
      with:
        virtualenvs-in-project: true

    - name: Upgrade pip & setuptools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools

    - name: Install Pre-Commit
      run: |
        python -m pip install pre-commit

    - name: Static Analysis
      run: |
        python -m pre_commit run --all-files
